### ISSUE TITLE
proxyConfig not working according to readme

### ISSUE THREAD

**Issue by dmilde** [redhat-cop/must-gather-operator#31]
Example in the readme says:
```
...
  proxyConfig:
    http_proxy: http://myproxy
    https_proxy: https://my_http_proxy
    no_proxy: master-api  
```

This creates an empty (proxyConfig {}) in the created mustgather resource.

Working for me is:
```
...
  proxyConfig:
    httpProxy: http://myproxy
    httpsProxy: https://my_http_proxy
```
