### ISSUE TITLE
curl: (3) Bad URL, colon is first character

### ISSUE THREAD

**Issue by tmorik** [redhat-cop/must-gather-operator#34]
It seems that must-gather created a tar.gz file but the upload fails with the following message:

```console
<...>
/must-gather/network_logs/overlappingrangeipreservations
/must-gather/network_logs/multi_networkpolicy
/must-gather/network_logs/cluster_scale
Uploading 'must-gather-20220518_211254Z.tar.gz' to Red Hat Customer Portal case <case number>
Enter host password for user '<username from case-management-creds>':
curl: (3) Bad URL, colon is first character
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0  4072    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  4113  100    41  100  4072     57   5719 --:--:-- --:--:-- --:--:--  5768
cat: /must-gather-upload/curl.log: No such file or directory
```

I have confirmed cURL with my credential and `api.access.redhat.com` is working from our cluster like below:

```console
sh-4.4$ curl -u '<username from case-management-creds>':'<password from case-management-creds>'  "https://api.access.redhat.com/rs/cases/<case number>/" -H 'Accept: text/plain' -v
<...>
< HTTP/1.1 200 OK
< Server: Apache-Coyote/1.1
< Cache-Control: private
< Expires: Wed, 31 Dec 1969 19:00:00 EST
< Access-Control-Allow-Credentials: true
< Access-Control-Max-Age: 1728000
< Access-Control-Allow-Headers: Content-Type, X-PINGOTHER, X-Omit, Authorization
< Location: https://access.redhat.com/rs/cases/<case number>
< Cache-Control: no-cache
< strata-code: 200
<...>
```
 
The deployed must-gather yaml is as follows:

```yaml
apiVersion: redhatcop.redhat.io/v1alpha1
kind: MustGather
metadata:
  name: example-mustgather
spec:
  caseID: '<case numver>'
  caseManagementAccountSecretRef:
    name: case-management-creds
```
