### ISSUE TITLE
Unable to collect and upload Openshift Cluster Logging information.

### ISSUE THREAD

**Issue by tmorik** [redhat-cop/must-gather-operator#35]
### Cluster Version
OCP 4.8 and 4.9

### Symptom
If an image for logging is specified for `mustGatherImages`, no container is created for logging and no logs are collected.

Tried images are below;
  - quay.io/openshift/origin-cluster-logging-operator
  - quay.io/openshift-logging/cluster-logging-operator
  - registry.redhat.io/openshift-logging/elasticsearch-rhel8-operator
  - Plus these images with tags, such as 4.8, 4.9 and latest
 
Example:

```
apiVersion: redhatcop.redhat.io/v1alpha1
kind: MustGather
metadata:
  name: example-mustgather-logging
spec:
  caseID: '<case number>'
  caseManagementAccountSecretRef:
    name: case-management-creds
  serviceAccountRef:
    name: must-gather-admin
  mustGatherImages:
    - quay.io/openshift/origin-cluster-logging-operator: latest
```

The MustGather object was created and the image was pulled, but the container "gather-0" created by the logging image did not start and stuck around until it timed out. 

```
$ oc get pods
NAME                                                       READY   STATUS     RESTARTS   AGE
example-mustgather-03233089-logging-5--1-459q2             0/1     Init:0/2   0          9m13s
must-gather-operator-controller-manager-6db646c465-lwn4n   2/2     Running    0          11d

$ oc describe pod example-mustgather-03233089-logging-5--1-459q2
<...>
Events:
  Type    Reason          Age        From               Message
  ----    ------          ----       ----               -------
  Normal  Scheduled       <invalid>  default-scheduler  Successfully assigned must-gather-operator/example-mustgather-03233089-logging-5--1-459q2 to mcs-klab-app-04.dmz
  Normal  AddedInterface  <invalid>  multus             Add eth0 [<ip>/23] from openshift-sdn
  Normal  Pulling         <invalid>  kubelet            Pulling image "quay.io/openshift/origin-cluster-logging-operator:latest"
  Normal  Pulled          <invalid>  kubelet            Successfully pulled image "quay.io/openshift/origin-cluster-logging-operator:latest" in 7.342187328s
  Normal  Created         <invalid>  kubelet            Created container gather-0
  Normal  Started         <invalid>  kubelet            Started container gather-0


$ oc logs -f  example-mustgather-03233089-logging-5--1-459q2 -c gather-0
<no output>
```

Other point I have been noticed is that, it looks like CPU usage was hitting its' `limit` resource (250m) so it seems CPU throttling was happening. like bellow picture:

 
![image](https://user-images.githubusercontent.com/64234643/172265021-b5b0afd7-ddc5-4dac-96a6-33967c20fd55.png)

Not so sure if this is normal or not. 

### Other remarks
The other example images in the README are working and uploaded without any problems:

  - quay.io/openshift/origin-must-gather:latest
  - quay.io/kubevirt/must-gather:latest
  - quay.io/ocs-dev/ocs-must-gather
